apiVersion: v1
kind: ReplicationController
metadata:
  name: syndromica
  labels:
    name: syndromica
spec:
  replicas: 4
  selector:
    name: syndromica
  template:
    metadata:
      labels:
        name: syndromica
    spec:
      containers:
      - name: syndromica
        image: ksonney/syndrobox:latest
        env:
          - name: NODE_DB_URI
            value: mongodb://mongosvc/syndrobox
        ports:
          - containerPort: 3000
            hostPort: 3000
            name: syndromica
